### ISSUE TITLE
Global-State implementation

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/svm#252]
We've decided to move the current Global-State component from `go-spacemesh` into the Rust

The core of SVM will consume its API and it should facilitate significantly the integration of SVM into the Full-Node.
The `go-svm` library will have to undergo the required changes and would become much more simple.

For now, we want to do the bare minimum required in order to achieve that. So using off-the-shelf solution such as [`parity-trie`] must be considered before writing everything from scratch.

In the future, we might rewrite this component to suit better our future needs (for example, using the new code to implement dynamic data-structures for SVM apps)

- [x] #328 (not necessary for 0.3 thanks to LinkedHashX)
- [x] #329 (not necessary for 0.3 thanks to LinkedHashX)
- [x] #330 
- [x] #358 

[`parity-trie`]: https://github.com/paritytech/trie

**Comment by neysofu** [comment]
We can close this :rocket:
