### ISSUE TITLE
Use the new wasmer `deterministic` feature

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/svm#27]
# Overview / Motivation
We want to use `wasmer` single-pass complier with the `deterministic` flag.

**Comment by YaronWittenstein** [comment]
It's a very old issue, I'm not fully sure it can be used. 

Maybe `Wasmer` needs to expose some `deterministic` feature flag that will propagate into the [`wasmparser`](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasmparser) crate used internally.

**Comment by YaronWittenstein** [comment]
We already validate there is no floats usage under the `validate_template` stage so this issue is of less importance.

**Comment by neysofu** [comment]
We already restrict nondeterministic features inside the `svm-program` crate. Besides, Wasmer doesn't expose such functionality anymore. Closing.
