### ISSUE TITLE
Fix the SVM Windows Artifact

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/svm#355]
@sudachen has pointed out that the current SVM Windows Artifact is corrupted and he suggested two ways to tackle it:

* Use [`dlltool`](https://sourceware.org/binutils/docs/binutils/dlltool.html)
@sudachen  - can you please elaborate what commands need to be used here?

* Use the `x86_64-pc-windows-gnu toolchain` explicitly when compiling to Windows.
@sudachen - is anything missing here?

@neysofu @moshababo @noamnelke  FYI

**Comment by sudachen** [comment]
There are the two different way. You can choose one of them. When you use *-windows-gnu toolchain it creates lib*.dll.a file automagically. By the way if you need/want by some reason use VS runtime/backend you can create lib*.a file in DWARF fromat required by golang compiler with dlltool, instead COFF *.lib created by VS toolchain.

**Comment by sudachen** [comment]
```
gendef.exe svm.dll
dlltool.exe -d svm.def -D svm.dll -l libsvm.a
```

**Comment by YaronWittenstein** [comment]
Thank you!
