### ISSUE TITLE
Implement `Increase Balance` for an `Account`

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/svm#377]
One of the requirements raised as part of the integration with `go-spacemesh` is that an Account should get a reward.
This is a `printing coins like` functionality doesn't involve any `sender` party.

The task is to implement an `increase_balance` functionality for the `Global State` and have it exposed in the FFI layer (to be consumed by `go-svm`)

**Comment by noamnelke** [comment]
Just making sure that `increase_balance` will be committed to a specific layer and be rewind-able.

**Comment by YaronWittenstein** [comment]
> Just making sure that `increase_balance` will be committed to a specific layer and be rewind-able.

of course

**Comment by neysofu** [comment]
Closed by https://github.com/spacemeshos/svm/pull/410.
