### ISSUE TITLE
FFI - Tracking leaked Receipts

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/svm#401]
The task of this issue is to extend SVM to track the number of leaked Receipts at any point in time.
It's the responsibility of the FFI layer client (e.g., the `go-svm`) to take care of releasing any leaked Receipt.

The definitions of Receipts are under this link:
https://github.com/spacemeshos/svm/tree/master/crates/types/src/receipt

However, we care about tracking encoded Receipts (i.e., a Receipt given as bytes)

Here the FFI layer calls for encoding the binary Receipt:
https://github.com/spacemeshos/svm/blob/master/crates/runtime-ffi/src/api.rs#L486

And this is where the leaking takes place:
https://github.com/spacemeshos/svm/blob/478d12fddfa87e6230a64010bfd3c0f24ad3164f/crates/runtime-ffi/src/result.rs#L61

## Reference Implementation:

Today we track leaked instances of `DefaultRuntime`:
* https://github.com/spacemeshos/svm/blob/master/crates/runtime-ffi/src/runtime_tracker.rs

This issue can use that as a reference.

## Testing

The current tests under the `runtime-ffi` crate should add assertions to track the number of leaked receipts.
(and see updates after releasing leaked receipts)

## Related Issues:
#391

**Comment by neysofu** [comment]
Resource tracking at the FFI boundary requires more `unsafe`-touching code and is error-prone. This is really not needed.
