### ISSUE TITLE
Extending `svm-codec` with the `Envelope`

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/svm#458]
As discussed in the [AA Transactions & SVM Integration](https://github.com/spacemeshos/SMIPS/issues/53)

The `Envelope` will consist of the following fields:

1. `version` - For versioning (to ease introducing new changes in the future).
Right now, we'll only accept the value 0x0 (for Genesis)
We can use a variable length-integer encoding here. 
Or allocate a fixed number of bytes

1. `type` - The Transaction type (`Deploy / Spawn / Call`)
A single byte seems the right choice.

1. `principal` - The `Address` of the Account paying for the Gas.
This will consume 20 bytes.

1. `amount` - For funding.
This field will be of type 64-bit integer (Big-Endian order).
We can use a variable length-integer encoding here. 

1. `tx_nonce` - For the tx nonce.
I think can use a variable length-integer encoding here (encoding up to say 128 bit).
The number 128-bit should suffice for any imaginable Generalized Nonce Scheme to be implemented.

1. `gas_limit` - Maximum units of Gas to be paid.
This field will be of type 64-bit integer (Big-Endian order).
We can use a variable length-integer encoding here. 

1. `gas_fee` - Fee per Unit of Gas.
This field will be of type 64-bit integer (Big-Endian order).
We can use a variable length-integer encoding here.

### Notes

* Right now, we have an `Envelope` type under the `svm-types`
https://github.com/spacemeshos/svm/blob/master/crates/types/src/transaction/envelope.rs

It should be extended to have the `version` and `type` fields as well.

* The `svm-codec` right now we have some working implementation for the `Envelope`.
https://github.com/spacemeshos/svm/blob/6edb73de199fafce0953f82af061ca1090ff911c/crates/codec/src/codec.rs#L137

When it was implemented we've thought about the encoding between `go-svm` and SVM.
Since we've decided that SVM will own the encoding of the `Envelope` the implementation might change
to be more compact. (and of course, it should adjust to include `version and `type` as well).

* I think it's worth adding a `Message` type to SVM under: https://github.com/spacemeshos/svm/tree/master/crates/types/src/transaction

The `Message` will be an `enum` that will hold one of the `Message` types:
```rust 
enum Message {
  Deploy(Template), 
  Spawn(SpawnAccount),
  Call(Transaction),
}
```

Now we could implement the `Codec` trait for `Message`.
This implementation will look on the `transaction type` and delegate the rest of the work to the current implementations of `Template/SpawnAccunt/Transaction` types.

* It might be worth renaming `SpawnAccount` to simply `Spawn`.
* Regarding `Transaction`, if it'll be renamed to `Call` we need to also rename this type:
https://github.com/spacemeshos/svm/blob/master/crates/runtime/src/runtime/call.rs
* If the `Transaction` name will be free again we could have:
```rust
struct Transaction {
  envelope: Envelope,
  message: Message
}
```

* Lastly, we could implement the `Codec` trait for `Transaction`
So decoding a `Transaction` will involve first decoding the `Envelope` part and then the `Message` part.

@lrettig FYI

**Comment by neysofu** [comment]
Not relevant anymore due to changes to transaction syntax.
