### ISSUE TITLE
Add C-API testing via C client 

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/svm#80]
# Overview / Motivation
We want to simulate a failed `exec app` transaction. The returned receipt should indicate that the transaction failed along with an error message.

# The Task
The task will require decoding a raw receipt of a failed transaction and printing the failure reason.

# Implementation Notes
1. The raw format of a receipt of a failed transaction can be found here:
https://github.com/spacemeshos/svm/blob/develop/crates/svm-runtime-c-api/src/receipt.rs#L15
2. Add a file named `panic.wasm` under `examples/c/wasm`

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/svm)

1. Introduce yourself on `svm` [dev chat channel](https://gitter.im/spacemesh-os/svm) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. The code must be formatted using [rustfmt](https://github.com/rust-lang/rustfmt)
4. You must write unit tests for all types and methods when submitting a component.
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by moshababo** [comment]
As discussed, this should be part of tests, and not as an example. 
Also, we should define many more scenarios.

Should this test suite be written in C or Rust?

**Comment by YaronWittenstein** [comment]
in `C`

**Comment by moshababo** [comment]
If you want you can specify additional test cases.

**Comment by YaronWittenstein** [comment]
Closing this issue.

Opened another one: #139
